import Vue from 'vue'
import { TabPane,Tabs,Button, Form, FormItem, Input, Card, Container, Header, Aside, Main, Menu, MenuItem, Table, TableColumn, Dialog, RadioGroup, Radio, Pagination, Select, Option,Upload } from 'element-ui'

Vue.use(Button)
Vue.use(TabPane)
Vue.use(Tabs)
Vue.use(Form)
Vue.use(FormItem)
Vue.use(Input)
Vue.use(Card)
Vue.use(Container)
Vue.use(Header)
Vue.use(Aside)
Vue.use(Main)
Vue.use(Menu)
Vue.use(MenuItem)
Vue.use(Table)
Vue.use(TableColumn)
Vue.use(Dialog)
Vue.use(Radio)
Vue.use(RadioGroup)
Vue.use(Pagination)
Vue.use(Select)
Vue.use(Option)
Vue.use(Upload)
